# Generated by Django 2.1.4 on 2018-12-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20181208_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdetails',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
